### ISSUE TITLE
CodeGen?

### ISSUE THREAD

**Issue by pcj** [stripe/skycfg#21]
This is *really* cool.  I was thinking of a similar project to be able to use strongly typed starlark structs just like you have here.  

However, based on comments in https://groups.google.com/forum/#!topic/starlark-go/l4XgedmC7l8, I was thinking of approaching it via codegen (a protoc plugin).

Anyway, I'm just curious of what you think of the codegen vs reflect approach here.  Was there a time during this implementation that you thought codegen was a better approach?   Thx.

**Comment by jmillikin-stripe** [comment]
Reflection was always the ideal implementation for Skycfg because it keeps a path open for dynamic schema loading. We want to be able to load new .proto schemas (or their binary equivalents) into an existing Skycfg binary without recompilation, which is impractical if the load is implemented with a protoc plugin.

The current implementation (using `reflect` on Go structs) exists because the Protobuf implementation for Go currently has no equivalent of [`google::protobuf::DynamicMessageFactory`](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.dynamic_message#DynamicMessageFactory) or [`google::protobuf::Reflection`](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.message#Reflection). When that is fixed upstream, Skycfg's remaining dependency on codegen can be removed.
